### ISSUE TITLE
Byte type

### ISSUE THREAD

**Issue by Mr-Auto** [zappatic/Spelunky2X64DbgPlugin#10]
signed one, you can set the value to 128 for some reason, and it's set to -128 (well, makes sense, but i don't think this should work this way)
![image](https://user-images.githubusercontent.com/36127424/120926737-72714f80-c6de-11eb-91a9-7f35931697f4.png)

also all negative numbers are shown wrong with 8bit,

+ unsigned dword doesn't have an input limit 
![image](https://user-images.githubusercontent.com/36127424/120927051-cb8db300-c6df-11eb-9849-97fdb3fee01a.png)

**Comment by zappatic** [comment]
* The display of signed 8 bit values should be fixed in the latest release
* Being able to enter 128 for signed 8-bit values: I explicitly tell the validator that the top value is 127, yet it decides to allow 128...
* The validators for UnsignedDword and both Qwords have been intentionally disabled, because the top and bottom value for validators are stored in signed integers.
